### ISSUE TITLE
Настроить тему сайта

### ISSUE THREAD

**Issue by unintended000** [unintended000/wordpress#4]
Необходимо настроить внешний вид сайта

**Comment by khadanovakv** [comment]
Выбранная тема не подходит

**Comment by khadanovakv** [comment]
Необходимо разделить главную страницу с странице записей

**Comment by khadanovakv** [comment]
Страница разделены
Добавлены новое и популярное

**Comment by unintended000** [comment]
Тема окончательно настроена.
